export const SIGNIN = "SIGNIN";
export const SIGNIN_PENDING = "SIGNIN_PENDING";
export const SIGNIN_FULFILLED = "SIGNIN_FULFILLED";
export const SIGNIN_REJECTED = "SIGNIN_REJECTED";

export const FETCH_ALL_NOMINEES_PENDING = "FETCH_ALL_NOMINEES_PENDING";
export const FETCH_ALL_NOMINEES_FULFILLED = "FETCH_ALL_NOMINEES_FULFILLED";
export const FETCH_ALL_NOMINEES_REJECTED = "FETCH_ALL_NOMINEES_REJECTED";

export const VOTE_PENDING = "VOTE_PENDING";
export const VOTE_FULFILLED = "VOTE_FULFILLED";
export const VOTE_REJECTED = "VOTE_REJECTED";

export const COMPLETE_VOTING = "COMPLETE_VOTING";
export const COMPLETE_VOTING_PENDING = "COMPLETE_VOTING_PENDING";
export const COMPLETE_VOTING_FULFILLED = "COMPLETE_VOTING_FULFILLED";
export const COMPLETE_VOTING_REJECTED = "COMPLETE_VOTING_REJECTED";
